services:
  backend:
    container_name: strava-backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${APP_PORT}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
  postgres:
    container_name: strava-db
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432